import { type FormEvent,useEffect,useState } from 'react'
import { Button,Card,PageHeader } from '@/components/ui'
import { useMyTeam } from '@/hooks/useMyTeam'
import { supabase } from '@/lib/supabase'

const empty={internship_company:'',project_name:'',one_line_summary:'',problem_statement:'',target_users:'',must_have:'',should_have:'',wont_have:'',tech_stack:'',internship_link:'',expected_outcome:'',four_week_plan:''}
export function ProjectPlanPage(){const{team,loading}=useMyTeam();const[form,setForm]=useState(empty);const[gpu,setGpu]=useState(false);const[message,setMessage]=useState('');const[submitted,setSubmitted]=useState(false)
useEffect(()=>{if(!team)return;supabase.from('project_plans').select('*').eq('team_id',team.id).maybeSingle().then(({data})=>{if(!data)return;setForm({internship_company:data.internship_company??'',project_name:data.project_name??'',one_line_summary:data.one_line_summary??'',problem_statement:data.problem_statement??'',target_users:data.target_users??'',must_have:join(data.must_have),should_have:join(data.should_have),wont_have:join(data.wont_have),tech_stack:join(data.tech_stack),internship_link:data.internship_link??'',expected_outcome:data.expected_outcome??'',four_week_plan:join(data.four_week_plan)});setGpu(data.gpu_required);setSubmitted(Boolean(data.submitted_at))})},[team])
async function save(event:FormEvent,submit=false){event.preventDefault();if(!team)return;const payload={team_id:team.id,team_name:team.name,...form,must_have:list(form.must_have).slice(0,3),should_have:list(form.should_have).slice(0,3),wont_have:list(form.wont_have),tech_stack:list(form.tech_stack),four_week_plan:list(form.four_week_plan),gpu_required:gpu,submitted_at:submit?new Date().toISOString():null};const{error}=await supabase.from('project_plans').upsert(payload,{onConflict:'team_id'});setMessage(error?.message??(submit?'기획서를 제출했습니다.':'임시 저장했습니다.'));if(!error)setSubmitted(submit)}
if(loading)return <p>불러오는 중…</p>;if(!team)return <PageHeader eyebrow="Student" title="프로젝트 기획서">팀 배정 후 작성할 수 있습니다.</PageHeader>;return <><PageHeader eyebrow={submitted?'Submitted':'Draft'} title="프로젝트 기획서">팀의 문제 정의와 4주 완성 범위를 작성합니다.</PageHeader><Card className="mt-8"><form onSubmit={event=>save(event,false)} className="grid gap-5 md:grid-cols-2"><Field label="인턴십 기업" value={form.internship_company} set={value=>setForm({...form,internship_company:value})}/><Field label="프로젝트명" value={form.project_name} set={value=>setForm({...form,project_name:value})}/><Field label="한 줄 정의" value={form.one_line_summary} set={value=>setForm({...form,one_line_summary:value})} wide/><Area label="해결하는 문제" value={form.problem_statement} set={value=>setForm({...form,problem_statement:value})}/><Area label="타겟 사용자" value={form.target_users} set={value=>setForm({...form,target_users:value})}/><Area label="Must Have (줄바꿈, 최대 3개)" value={form.must_have} set={value=>setForm({...form,must_have:value})}/><Area label="Should Have (줄바꿈, 최대 3개)" value={form.should_have} set={value=>setForm({...form,should_have:value})}/><Area label="Won't Have" value={form.wont_have} set={value=>setForm({...form,wont_have:value})}/><Area label="기술 스택" value={form.tech_stack} set={value=>setForm({...form,tech_stack:value})}/><Area label="4주 완성 계획 (주차별 줄바꿈)" value={form.four_week_plan} set={value=>setForm({...form,four_week_plan:value})}/><Area label="인턴십 연결고리" value={form.internship_link} set={value=>setForm({...form,internship_link:value})}/><Area label="기대 성과" value={form.expected_outcome} set={value=>setForm({...form,expected_outcome:value})}/><label className="flex items-center gap-2 text-sm font-bold md:col-span-2"><input type="checkbox" checked={gpu} onChange={e=>setGpu(e.target.checked)}/>GPU 사용</label><div className="flex gap-2 md:col-span-2"><Button>임시 저장</Button><Button type="button" className="bg-emerald-700" onClick={event=>save(event as unknown as FormEvent,true)}>제출</Button></div></form>{message&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{message}</p>}</Card></>}
const cls='mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm';function Field({label,value,set,wide=false}:{label:string;value:string;set:(v:string)=>void;wide?:boolean}){return <label className={`text-sm font-bold ${wide?'md:col-span-2':''}`}>{label}<input className={cls} value={value} onChange={e=>set(e.target.value)}/></label>}function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-sm font-bold">{label}<textarea className={`${cls} min-h-28`} value={value} onChange={e=>set(e.target.value)}/></label>}function list(value:string){return value.split('\n').map(v=>v.trim()).filter(Boolean)}function join(value:unknown){return Array.isArray(value)?value.join('\n'):''}
