create extension if not exists pgcrypto;
create type public.app_role as enum ('professor','student','researcher');
create type public.semester_term as enum ('spring','summer','fall','winter');
create type public.job_group as enum ('sw_engineering','sw_development','ai_development');
create type public.project_status as enum ('planning','design','implementation','presentation','completed');
create type public.report_status as enum ('draft','submitted','reviewed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text not null unique,name text not null,student_no text,department text,phone text,role public.app_role not null default 'student',job_group public.job_group,avatar_url text,bio text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.semesters (id uuid primary key default gen_random_uuid(),year int not null,term public.semester_term not null,course_code text,course_name text not null,section text,title text not null,is_active boolean not null default false,start_date date,end_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.participants (id uuid primary key default gen_random_uuid(),semester_id uuid not null references public.semesters(id) on delete cascade,profile_id uuid references public.profiles(id) on delete set null,email text not null,name text not null,student_no text,department text,phone text,job_group public.job_group,memo text,is_registered boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(semester_id,email));
create table public.teams (id uuid primary key default gen_random_uuid(),semester_id uuid not null references public.semesters(id) on delete cascade,name text not null,topic text,internship_company text,project_name text,description text,leader_profile_id uuid references public.profiles(id) on delete set null,status public.project_status not null default 'planning',notion_url text,github_url text,demo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(semester_id,name));
create table public.team_members (id uuid primary key default gen_random_uuid(),team_id uuid not null references public.teams(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,role_in_team text,job_group public.job_group,is_leader boolean not null default false,created_at timestamptz not null default now(),unique(team_id,profile_id));
create unique index one_leader_per_team on public.team_members(team_id) where is_leader;
create table public.project_plans (id uuid primary key default gen_random_uuid(),team_id uuid not null unique references public.teams(id) on delete cascade,team_name text,internship_company text,project_name text,one_line_summary text,problem_statement text,target_users text,must_have jsonb not null default '[]',should_have jsonb not null default '[]',wont_have jsonb not null default '[]',tech_stack jsonb not null default '[]',gpu_required boolean not null default false,four_week_plan jsonb not null default '[]',internship_link text,expected_outcome text,submitted_at timestamptz,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.weekly_reports (id uuid primary key default gen_random_uuid(),team_id uuid not null references public.teams(id) on delete cascade,week_no int not null check(week_no>0),title text not null,progress_summary text,completed_items jsonb not null default '[]',next_items jsonb not null default '[]',issues text,support_needed text,status public.report_status not null default 'draft',submitted_by uuid references public.profiles(id) on delete set null,submitted_at timestamptz,reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(team_id,week_no));
create table public.project_artifacts (id uuid primary key default gen_random_uuid(),team_id uuid not null references public.teams(id) on delete cascade,title text not null,artifact_type text not null,url text,file_path text,description text,submitted_by uuid references public.profiles(id) on delete set null,submitted_at timestamptz not null default now(),created_at timestamptz not null default now());
create table public.announcements (id uuid primary key default gen_random_uuid(),semester_id uuid references public.semesters(id) on delete cascade,title text not null,content text not null,pinned boolean not null default false,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create or replace function public.current_user_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;
create or replace function public.is_professor() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='professor')$$;
create or replace function public.is_researcher_or_professor() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role in ('professor','researcher'))$$;
create or replace function public.is_team_member(target_team_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.team_members where team_id=target_team_id and profile_id=auth.uid())$$;
revoke all on function public.current_user_role() from public; revoke all on function public.is_professor() from public; revoke all on function public.is_researcher_or_professor() from public; revoke all on function public.is_team_member(uuid) from public;
grant execute on function public.current_user_role() to authenticated; grant execute on function public.is_professor() to authenticated; grant execute on function public.is_researcher_or_professor() to authenticated; grant execute on function public.is_team_member(uuid) to authenticated;

alter table public.profiles enable row level security; alter table public.semesters enable row level security; alter table public.participants enable row level security; alter table public.teams enable row level security; alter table public.team_members enable row level security; alter table public.project_plans enable row level security; alter table public.weekly_reports enable row level security; alter table public.project_artifacts enable row level security; alter table public.announcements enable row level security;
create policy profiles_read on public.profiles for select using(id=auth.uid() or public.is_researcher_or_professor() or exists(select 1 from public.team_members me join public.team_members peer on peer.team_id=me.team_id where me.profile_id=auth.uid() and peer.profile_id=profiles.id));
create policy profiles_professor_all on public.profiles for all using(public.is_professor()) with check(public.is_professor());
create policy profiles_self_update on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=public.current_user_role());
create policy semesters_read on public.semesters for select to authenticated using(true); create policy semesters_professor_all on public.semesters for all using(public.is_professor()) with check(public.is_professor());
create policy participants_staff_read on public.participants for select using(public.is_researcher_or_professor()); create policy participants_self_read on public.participants for select using(profile_id=auth.uid()); create policy participants_professor_all on public.participants for all using(public.is_professor()) with check(public.is_professor());
create policy teams_read on public.teams for select using(public.is_researcher_or_professor() or public.is_team_member(id)); create policy teams_professor_all on public.teams for all using(public.is_professor()) with check(public.is_professor());
create policy team_members_read on public.team_members for select using(public.is_researcher_or_professor() or public.is_team_member(team_id)); create policy team_members_professor_all on public.team_members for all using(public.is_professor()) with check(public.is_professor());
create policy plans_read on public.project_plans for select using(public.is_researcher_or_professor() or public.is_team_member(team_id)); create policy plans_professor_all on public.project_plans for all using(public.is_professor()) with check(public.is_professor()); create policy plans_team_insert on public.project_plans for insert with check(public.is_team_member(team_id)); create policy plans_team_update on public.project_plans for update using(public.is_team_member(team_id)) with check(public.is_team_member(team_id));
create policy reports_read on public.weekly_reports for select using(public.is_researcher_or_professor() or public.is_team_member(team_id)); create policy reports_professor_all on public.weekly_reports for all using(public.is_professor()) with check(public.is_professor()); create policy reports_team_insert on public.weekly_reports for insert with check(public.is_team_member(team_id) and submitted_by=auth.uid()); create policy reports_team_update on public.weekly_reports for update using(public.is_team_member(team_id)) with check(public.is_team_member(team_id));
create policy artifacts_read on public.project_artifacts for select using(public.is_researcher_or_professor() or public.is_team_member(team_id)); create policy artifacts_professor_all on public.project_artifacts for all using(public.is_professor()) with check(public.is_professor()); create policy artifacts_team_insert on public.project_artifacts for insert with check(public.is_team_member(team_id) and submitted_by=auth.uid()); create policy artifacts_team_update on public.project_artifacts for update using(public.is_team_member(team_id)) with check(public.is_team_member(team_id)); create policy artifacts_team_delete on public.project_artifacts for delete using(public.is_team_member(team_id));
create policy announcements_read on public.announcements for select to authenticated using(true); create policy announcements_professor_all on public.announcements for all using(public.is_professor()) with check(public.is_professor());

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at(); create trigger semesters_updated before update on public.semesters for each row execute function public.set_updated_at(); create trigger participants_updated before update on public.participants for each row execute function public.set_updated_at(); create trigger teams_updated before update on public.teams for each row execute function public.set_updated_at(); create trigger plans_updated before update on public.project_plans for each row execute function public.set_updated_at(); create trigger reports_updated before update on public.weekly_reports for each row execute function public.set_updated_at(); create trigger announcements_updated before update on public.announcements for each row execute function public.set_updated_at();
