import {ArrowLeft,CalendarDays,CheckCircle2,FileText,UserRound} from 'lucide-react'
import {useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Card,PageHeader} from '@/components/ui'
import {supabase} from '@/lib/supabase'

interface ReportDetail{id:string;team_id:string;week_no:number;report_date:string;title:string;progress_summary:string|null;completed_items:unknown;next_items:unknown;issues:string|null;support_needed:string|null;status:string;submitted_at:string|null;teams:{name:string;project_name:string|null}|null;submitter:{name:string;email:string}|null}

export function ReportDetailPage(){const{reportId}=useParams();const[report,setReport]=useState<ReportDetail|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{if(!reportId)return;supabase.from('weekly_reports').select('id,team_id,week_no,report_date,title,progress_summary,completed_items,next_items,issues,support_needed,status,submitted_at,teams(name,project_name),submitter:profiles!weekly_reports_submitted_by_fkey(name,email)').eq('id',reportId).single().then(({data,error:queryError})=>{if(queryError)setError(queryError.message);else setReport(data as unknown as ReportDetail);setLoading(false)})},[reportId]);if(loading)return <p className="text-slate-500">보고서 내용을 불러오는 중…</p>;if(error||!report)return <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error||'보고서를 찾을 수 없습니다.'}</p>;return <><Link to=".." relative="path" className="mb-5 inline-flex items-center gap-1 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>팀 보고서 목록으로</Link><PageHeader eyebrow={`${report.week_no}주차 · ${report.report_date}`} title={report.title}>{report.teams?.name} · {report.teams?.project_name||'프로젝트 미정'}</PageHeader><div className="mt-8 grid gap-5 sm:grid-cols-3"><Meta icon={CalendarDays} label="작성일" value={report.report_date}/><Meta icon={UserRound} label="제출자" value={report.submitter?.name||'—'}/><Meta icon={CheckCircle2} label="상태" value={statusName(report.status)}/></div><Card className="mt-6"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-inha-700"/><h2 className="font-black">진행 요약</h2></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700">{report.progress_summary||'진행 요약 없음'}</p></Card><div className="mt-6 grid gap-5 lg:grid-cols-2"><Section title="완료 항목" value={listText(report.completed_items)}/><Section title="다음 계획" value={listText(report.next_items)}/><Section title="이슈" value={report.issues||'없음'} alert={Boolean(report.issues)}/><Section title="지원 요청" value={report.support_needed||'없음'} alert={Boolean(report.support_needed)}/></div></>}

function Meta({icon:Icon,label,value}:{icon:typeof CalendarDays;label:string;value:string}){return <Card><Icon className="h-5 w-5 text-inha-700"/><p className="mt-3 text-xs font-bold text-slate-500">{label}</p><strong className="mt-1 block">{value}</strong></Card>}
function Section({title,value,alert=false}:{title:string;value:string;alert?:boolean}){return <Card className={alert?'border-amber-200 bg-amber-50':''}><h2 className={`font-black ${alert?'text-amber-800':''}`}>{title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-600">{value}</p></Card>}
function listText(value:unknown){return Array.isArray(value)?value.map((item,index)=>`${index+1}. ${item}`).join('\n'):String(value??'없음')}
function statusName(status:string){return({draft:'작성중',submitted:'제출',reviewed:'검토완료'} as Record<string,string>)[status]??status}
